# Generated by Django 5.2.9 on 2026-01-03 00:39

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.update_or_create(name='생산팀')
    Role.objects.update_or_create(name='자재담당자')

def revert_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(name__in=['생산팀', '자재담당자']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles, revert_roles),
    ]
