# Generated by Django 5.2.9 on 2025-12-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='거래처명')),
                ('business_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자번호')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='품목명')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='품목코드')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='단가')),
                ('production_facility', models.CharField(blank=True, max_length=50, null=True, verbose_name='생산동')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
            ],
            options={
                'verbose_name': '거래처별 취급 품목',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
