# Generated by Django 5.0.2 on 2024-03-01 07:12

from django.db import migrations

def create_internal_sales_customer(apps, schema_editor):
    """
    내부 영업팀용 가상 거래처를 생성합니다.
    """
    Customer = apps.get_model('masters', 'Customer')
    Customer.objects.get_or_create(
        name='내부 영업팀',
        defaults={'business_id': '000-00-00000', 'is_active': False}
    )

def remove_internal_sales_customer(apps, schema_editor):
    """
    내부 영업팀용 가상 거래처를 삭제합니다.
    """
    Customer = apps.get_model('masters', 'Customer')
    try:
        customer = Customer.objects.get(name='내부 영업팀')
        customer.delete()
    except Customer.DoesNotExist:
        pass # 이미 없으면 아무것도 하지 않음

class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_salesfavoriteproduct'),
    ]

    operations = [
        migrations.RunPython(create_internal_sales_customer, remove_internal_sales_customer),
    ]