# Generated by Django 5.2.9 on 2025-12-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_add_internal_sales_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name': '품목', 'verbose_name_plural': '품목들'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, verbose_name='정렬 순서'),
        ),
    ]
