# Generated by Django 5.2.9 on 2026-01-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_product_options_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='부자재명')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='부자재코드')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='바코드')),
                ('image', models.ImageField(blank=True, null=True, upload_to='raw_materials/', verbose_name='이미지')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='단가')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '부자재',
                'verbose_name_plural': '부자재들',
            },
        ),
    ]
