# Generated by Django 5.2.9 on 2026-01-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_rawmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='bundles_per_box',
            field=models.PositiveIntegerField(default=1, verbose_name='박스당 번들수'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='units_per_bundle',
            field=models.PositiveIntegerField(default=1, verbose_name='번들당 단위수'),
        ),
    ]
