# Generated by Django 5.2.9 on 2026-01-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_rawmaterial_bundles_per_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='bundles_per_box',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='units_per_bundle',
        ),
    ]
