# Generated by Django 5.2.9 on 2026-01-03 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0005_rawmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': '부자재 발주',
                'verbose_name_plural': '부자재 발주 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('material_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.materialorder', verbose_name='부자재 발주')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.rawmaterial', verbose_name='품목')),
            ],
            options={
                'verbose_name': '부자재 발주 품목',
                'verbose_name_plural': '부자재 발주 품목들',
            },
        ),
    ]
