# Generated by Django 5.2.9 on 2026-01-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='요청납기일'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
