# Generated by Django 5.2.9 on 2026-01-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_materialorder_requested_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorderitem',
            name='box_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='박스 수량'),
        ),
        migrations.AddField(
            model_name='materialorderitem',
            name='bundle_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='번들 수량'),
        ),
        migrations.AddField(
            model_name='materialorderitem',
            name='each_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='낱개 수량'),
        ),
        migrations.AlterField(
            model_name='materialorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='총 수량'),
        ),
    ]
