# Generated by Django 4.0.4 on 2026-01-05 08:35

from django.db import migrations

def migrate_quantity_to_each(apps, schema_editor):
    MaterialOrderItem = apps.get_model('production', 'MaterialOrderItem')
    for item in MaterialOrderItem.objects.all():
        if item.quantity is not None:
            item.each_quantity = item.quantity
            item.save(update_fields=['each_quantity'])

def reverse_migrate(apps, schema_editor):
    # This is a one-way migration, but for completeness, 
    # we can try to move it back. This assumes new orders have total quantity in each_quantity.
    MaterialOrderItem = apps.get_model('production', 'MaterialOrderItem')
    for item in MaterialOrderItem.objects.all():
        item.quantity = item.each_quantity
        item.save(update_fields=['quantity'])

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_materialorderitem_box_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_quantity_to_each, reverse_code=reverse_migrate),
    ]