# Generated by Django 5.2.9 on 2026-01-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_migrate_quantity_to_each'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorderitem',
            name='quantity',
        ),
    ]
