# Generated by Django 5.2.9 on 2025-12-16 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '등록'), ('UPDATE', '수정'), ('DELETE', '삭제'), ('FULFILL', '수주 완료')], max_length=10, verbose_name='작업 유형')),
                ('model_name', models.CharField(max_length=50, verbose_name='대상 모델')),
                ('object_id', models.IntegerField(verbose_name='객체 ID')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='변경 상세 내역')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='작업 시각')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '감사 로그',
                'ordering': ['-timestamp'],
            },
        ),
    ]
