# Generated by Django 5.2.9 on 2025-12-16 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_delivery_date', models.DateField(verbose_name='요청 납기일')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발주 등록일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placed_orders', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.customer', verbose_name='거래처')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(verbose_name='요청 수량')),
                ('fulfilled_quantity', models.PositiveIntegerField(default=0, verbose_name='완료 수량')),
                ('status', models.CharField(choices=[('대기', '대기'), ('부분완료', '부분완료'), ('완료', '완료')], default='대기', max_length=10, verbose_name='생산 상태')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.orderheader', verbose_name='발주 헤더')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product', verbose_name='품목')),
            ],
        ),
    ]
