# Generated by Django 5.2.9 on 2025-12-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='production_facility',
            field=models.CharField(default='A동', max_length=50, verbose_name='생산동'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='production_facility',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='생산동'),
        ),
    ]
