# Generated by Django 5.2.9 on 2025-12-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderheader_production_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='production_facility',
            field=models.CharField(default='A동', max_length=50, verbose_name='생산동'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료')], default='PENDING', max_length=20, verbose_name='생산 상태'),
        ),
    ]
