# Generated by Django 5.2.9 on 2025-12-17 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderline_production_facility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='변경 유형')),
                ('description', models.TextField(verbose_name='변경 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='변경 일시')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.orderline')),
            ],
        ),
    ]
